
 

name: CI

on:
  push:
    tags:
    - '*'
    branches:
    - '**' 
jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Build
        run: go mod tidy && go build .

